site/myauth/urls.py
from django.conf.urls import patterns, include, url
from views import main, login_user, myauth_logout

urlpatterns = patterns('',
    url(r'^main/$', main, name='main'),
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', myauth_logout, name='logout'),
)

site/retocid/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#import fitapp

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'retocid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^fitbit/', include('fitapp.urls')),
    url(r'^my/', include('myauth.urls', namespace='my')),
    url(r'^r/', include('reports.urls')),
    url(r'^$', 'myauth.views.login_user'),
)

site/myauth/models.py
from django.db import models

# Create your models here.

site/myauth/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy, reverse

# Create your views here.

from django.http import *
from django.shortcuts import render_to_response,redirect
from django.template import RequestContext
#from birthdayreminder.models import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.views.decorators.cache import cache_page

@cache_page(0)
def login_user(request):
    logout(request)
    username = password = ''
    context = {}
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('my:main'))
        else:
            context['error'] = u'El usuario no se encontró o es incorrecto.'
    return render_to_response('login.html', context,
            context_instance=RequestContext(request))

@login_required(login_url=reverse_lazy('my:login'))
def main(request):
    return render(request, "integration.html")

def myauth_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('my:login'))

site/myauth/templates/base.html
{% extends 'bootstrap.html' %}

{% load url from future %}

{% load bootstrap3 %}

{% block bootstrap3_extra_head %}
{% block extrahead %}{% endblock %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
     (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
 
  ga('create', 'UA-63194829-1', 'auto');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
     
</script>
{% endblock %}

{% block bootstrap3_content %}
    <div class="container">
        <h1>{% block title %}(no title){% endblock %}</h1>

        {% bootstrap_messages %}

        {% block content %}(no content){% endblock %}
    </div>

{% endblock %}

site/myauth/templates/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

site/myauth/templates/graficas.html
    <li><a href="{% url 'promedios' 2014 11 17 7 1 %}">Ver promedios por país - Semana 1</a></li>
    <li><a href="{% url 'promedios' 2014 11 24 7 2 %}">Ver promedios por país - Semana 2</a></li>
    <li><a href="{% url 'promedios' 2014 12 1 7 3 %}">Ver promedios por país - Semana 3</a></li>
    <li><a href="{% url 'promedios' 2014 12 8 7 4 %}">Ver promedios por país - Semana 4</a></li>

site/myauth/templates/integration.html
{% extends 'base.html' %}


{% block title %}

{% endblock %}

{% block content %}
{% load url from future %}
{% load fitbit %}

<div class="container">
    <div style="padding: 40px 15px; text-align: center;">
        {% if request.user|is_integrated_with_fitbit %}
            <iframe src="https://www.fitbit.com/logout" style="visibility: hidden;" width="0" height="0"></iframe>
            {% if request.user.userfitbit.myuserfitbit.authorized %}
                <h2>Autorizado ¡Gracias!</h2>
            {% else %}
                <h2>Error: Favor de autorizar de nuevo</h2>
            {% endif %}

        <ul class="list-unstyled">
            <li><a href="{% url 'fitbit-login' %}">Autorizar de nuevo</a></li>
            <li><a href="{% url 'steps' %}">Ver pasos de la última semana</a></li>
        {% else %}
            <li><a href="{% url 'fitbit-login' %}">Autorizar uso de Fitbit</a></li>
        {% endif %}
            {% include "graficas.html" %}
            <li><a href="{% url 'my:logout' %}">Salir</a></li>
        </ul>
    </div>
</div>
{% endblock %}

site/myauth/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}

{% endblock %}

{% block content %}

<div class="container">
        <form class="form-signin" role="form" name="LoginForm" action="/my/login/" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}
        <h2 class="form-signin-heading">Enlazar <strong>Reto CID</strong></h2>

        {% if error %}
            <strong>{{ error }}</strong>
        {% endif %}

        <input type="text" id="username" name="username" class="form-control" placeholder="Username sin @iadb.org" required autofocus>
        <input type="hidden" name="password" value="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      </form>

</div> <!-- /container -->

<div class="container">
    <div class="row" style="padding: 40px 15px;">
        <div class="col-md-4 center-block" style="float: none;">
            <ul>
            {% include "graficas.html" %}
            </ul>
        </div>
    </div>
</div>

<div class="container">
<div class="row">
  <div class="col-md-3"></div>
  <div class="text-center col-md-6">
        <img src="{% static "img/dominicana_1.png" %}" alt="...">
        <img src="{% static "img/guatemala_1.png" %}" alt="...">
        <img src="{% static "img/costarica_1.png" %}" alt="...">
        <img src="{% static "img/nicaragua_1.png" %}" alt="...">
        <img src="{% static "img/mexico_1.png" %}" alt="...">
        <img src="{% static "img/panama_1.png" %}" alt="...">
        <img src="{% static "img/elsalvador_1.png" %}" alt="...">
        <img src="{% static "img/honduras_1.png" %}" alt="...">
        <img src="{% static "img/belize_1.png" %}" alt="...">
        <img src="{% static "img/hq_1.png" %}" alt="...">
  </div>
</div>
</div>

{% endblock %}

site/myauth/templates/success.html
{% extends "website-base.html" %}
{% block main %}
<p>Welcome, {{ user.username }}.</p>
{% endblock %}